## Together, these functions either compute and cache the inverse of a new
## matrix or retrieve the inverse of a matrix that was computed previously.  

## makeCacheMatrix creates a list of functions that facilitate input,
## storage, and retrieval of a matrix and its inverse.

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set_matrix <- function(y) {
                x <<- y
                i <<- NULL
        }
        get_matrix <- function() x
        set_inverse <- function(inverse) i <<- inverse
        get_inverse <- function() i
        list(set_matrix = set_matrix, 
             get_matrix = get_matrix, 
             set_inverse = set_inverse, 
             get_inverse = get_inverse)
}


## cacheSolve retrieves the inverse of a matrix if it was computed
## previously or computes and caches the inverse of a new matrix using the
## corresponding list generated by makeCacheMatrix. 

cacheSolve <- function(x, ...) {
        i <- x$get_inverse()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get_matrix()
        i <- solve(data)
        x$set_inverse(i)
        i
}